import { type NextPage } from "next";
import Head from "next/head";

import Header from "~/components/overall/header";
import Sidebar from "~/components/overall/sidebar";
import SimpleSlider from "~/components/home/carousel"
import Testimonials from "~/components/home/testimonials";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-gray-200 min-h-screen max-h-screen max-w-[100vw] overflow-x-hidden overflow-y-hidden ">
        <div className="flex flex-col">
          <Header/>
          <div className="flex flex-row">
            <Sidebar/>
            <Content/>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {

  return(
    <div className="max-h-[95vh] overflow-x-hidden">
      <h1>CART</h1>      
      <button className="relative w-fit bg-red-500 hover:bg-red-400 text-white px-3 py-1 text-lg text-center rounded-2xl outline-none transition">delete</button>
      <br/>
      <button className="relative w-fit bg-red-500 hover:bg-red-400 text-white px-3 py-1 text-lg text-center rounded-2xl outline-none transition">delete all</button>

    </div>
  )
}
