import { type NextPage } from "next";
import Head from "next/head";

import HeaderNEW from "~/components/overall/headerNEW";
import SimpleSlider from "~/components/home/carousel"
import Testimonials from "~/components/home/testimonials";
import HoverImages from "~/components/overall/hoverImages";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-gray-200 min-h-screen overflow-x-hidden overflow-y-hidden">
        <HeaderNEW/>
          <Content/>
      </main>
    </>
  );
};

export default Home;

const Content: React.FC = () => {

  return(
    <div>
      <img src="/ExploreSamples.png" alt="Banner" className="m-auto w-full mb-[-2%]"/>
      <div className="text-center">
        <button className="bg-gray-500 px-2 rounded text-lg">Click here!</button>
      </div>
      <div className="flex flex-row w-full items-center justify-center mt-5">
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-2">Welcome to CBH! HEADLINE</h1>
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <div className="flex flex-row w-full items-center justify-center">
        <h1 className="text-xl whitespace-nowrap mx-20 mb-2">Welcome to CBH! subheader</h1>
      </div>
      <div className="mt-5 pt-5">
        <SimpleSlider/>
      </div>
      <div className="flex flex-row w-full items-center justify-center mt-5 gap-96 mb-10">
        <img src="/drittens.png" alt="" className="w-1/3 mx-10" width={260} height={300}/>
        <img src="/drittens.png" alt="" className="w-1/3 mx-10" width={260} height={300}/>
        <img src="/drittens.png" alt="" className="w-1/3 mx-10" width={260} height={300}/>
      </div>
      <HoverImages/>
      <div className="flex flex-row w-full items-center justify-center mt-5 gap-72 my-10 bg-white">
        <img src="/social media.png" alt=""></img>
        <button className="bg-gray-500 rounded px-5 py-2">What People say about us</button>
        <img src="/paymentsnew.png" alt="" width={260} height={300}></img>
      </div>
      <div className="w-full border-2 border-solid h-0 border-gray-400 rounded-3xl m-5"></div>
      <div className="text-center">
        <h1 className="text-4xl">Impressum</h1>
      </div>

    </div>
  )
}
