import { type NextPage } from "next";
import Head from "next/head";

import HeaderNEW from "~/components/overall/headerNEW";
import SimpleSlider from "~/components/home/carousel"
import Testimonials from "~/components/home/testimonials";
import HoverImages from "~/components/overall/hoverImages";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <div className="bg-gray-200 min-h-screen overflow-hidden">
        <HeaderNEW/>
        <Content/>
      </div>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const [searchQuery, setSearchQuery] = useState<string>("");
  const router = useRouter();

  const onSearch = (event: React.FormEvent) => {
    event.preventDefault();

    const encodedSearchQuery = encodeURI(searchQuery);
    void router.push(`/search?q=${encodedSearchQuery}`);
  }

  return(
<div className="relative">
  <Image src="/home/BannerNoFont.png" alt="Banner" width={1920} height={350} className="w-full filter blur-sm" />
  <div className="absolute inset-20 pb-20 flex justify-center ">
        <div className="text-center">

          <h1 className="text-white text-6xl font-bold">
          <span style={{ textShadow: '0px 0px 4px rgba(0, 0, 0, 0.2)', WebkitTextStroke: '0.4px black' }}>
          Explore the Abundance
          </span>
          </h1>

          <p className="text-white text-2xl font-bold mt-4">
          <span style={{ textShadow: '0px 0px 4px rgba(0, 0, 0, 0.2)', WebkitTextStroke: '0.4px black' }}>
          Find the perfect human biospecmens for you.
          </span>
          </p>

          <div className="text-center justify-center">
            <div className="px-4 py-2 rounded flex items-center justify-center mt-10">
              <form onSubmit={onSearch}>
                <input 
                  value={searchQuery} 
                  onChange={event => setSearchQuery(event.target.value)} 
                  className="text-lg font-semibold bg-white bg-opacity-60 placeholder-[#164A41] text-[#164A41] border-l border-t border-b border-solid border-white rounded-l-lg flex-grow-1" 
                  placeholder='Start exploring'>
                </input>
              </form>
              <button className="bg-[#164A41] px-2 rounded-tr-lg rounded-br-lg text-lg px-4 py-1">
                <svg width="12" height="21" viewBox="0 0 20 36" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path opacity="0.4" d="M13.2156 9.00221L0 18.6931L0 33.0375C0 35.4922 3.03565 36.7195 4.81522 34.9808L18.371 21.7359C20.543 19.6136 20.543 16.1617 18.371 14.0394L13.2156 9.00221Z" fill="black"/>
                  <path d="M0 2.76626V18.6961L13.2156 9.00524L4.81522 0.797406C3.03565 -0.915755 0 0.311585 0 2.76626Z" fill="black"/>
                </svg>
              </button>
            </div>
          </div>

        </div>
      </div>
    

      <div className="flex flex-row w-full items-center justify-center mt-10">
        <div className="w-full  h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-2">Welcome to Central Biohub</h1>
        <div className="w-full  h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <div className="flex flex-row w-full items-center justify-center">
        <h1 className="text-xl whitespace-nowrap mx-20 mb-2">the world`s smartest biospecimen marketplace</h1>
      </div>
      <div className="mt-5 pt-5">
        <SimpleSlider/>
      </div>
      <div className="flex flex-row w-full items-center justify-center mt-10">
        <h1 className="relative">
          <span className="inline-block font-poppins headline">lorem ipsum</span>
          <span className="rounded-full absolute -bottom-1 left-1/2 transform -translate-x-1/2 h-[2px] w-20 bg-[#164A41]"></span>
        </h1>
      </div>
      <div className="grid grid-cols-3 w-full items-center justify-center mt-5 ml-[128px] mb-10">
        <div>
          <img src="/placeholderTest.jpg" alt="" className="border-b-2 border-[#164A41] custom-shadow w-max object-contain mx-16" width={225} height={210}/>
          <div className="w-[225px] bg-white p-6 mx-16 flex flex-col"><div className="text-center font-poppins items-start h-full">lorem ipsum</div></div>
        </div> 
        <div>
          <img src="/placeholderTest.jpg" alt="" className="border-b-2 border-[#164A41] custom-shadow w-max object-contain mx-16" width={225} height={210}/>
          <div className="w-[225px] bg-white p-6 mx-16 flex flex-col"><div className="text-center font-poppins items-start h-full">lorem ipsum</div></div>
        </div> 
        <div>
          <img src="/placeholderTest.jpg" alt="" className="border-b-2 border-[#164A41] custom-shadow w-fit object-contain mx-16" width={225} height={210}/>
          <div className="w-[225px] bg-white p-6 mx-16 flex flex-col"><div className="text-center font-poppins items-start h-full">lorem ipsum</div></div>
        </div> 
      </div>
      <div className="flex flex-row w-full items-center justify-center my-10">
        <h1 className="relative">
          <span className="inline-block font-poppins headline">Our Partners - Your Suppliers</span>
          <span className="rounded-full absolute -bottom-1 left-1/2 transform -translate-x-1/2 h-[2px] w-20 bg-[#164A41]"></span>
        </h1>
      </div>
      <div>
        <div className="flex flex-row w-full h-fit items-center justify-center my-6">
          <img src="/placeholdergreen.png" alt="" className="custom-shadow opacity-50" width={1920} height={280}/>
        </div>
      </div>
      <div className="flex items-center justify-center mt-5 m-auto mb-10">
        <div className="text-center font-poppins headline text-[#164A41] mx-4">
          <div className="inline-block px-32">Follow Our Journey!</div>
            <div className="border-2 border-[#164A41] p-4 rounded-lg mt-2 w-full flex flex-wrap">
              <img src="facebook.png" alt="" className="mx-4" />
              <img src="twitter.png" alt="" className="mx-4" />
              <img src="youtube.png" alt="" className="mx-4" />
              <img src="instagram.png" alt="" className="mx-4" />
              <img src="linkedin.png" alt="" className="mx-4" />
            </div>
        </div>
        <div className="text-center font-poppins headline text-[#164A41] mx-16">
          <div className="inline-block px-[140px] ">Testimonials</div>
            <div className="border-2 border-[#164A41] rounded-lg mt-2 w-full flex justify-end">
              <div className="text-center font-semibold flex-1 flex flex-col justify-center font-poppins text-2xl">
                <div>Look What People</div>
                <div>Say About Us!</div>
              </div>
            <button className="bg-[#F1B24A] border-[#F1B24A] rounded-tr-lg rounded-br-lg text-lg px-8 py-[32px] flex h-full">
                <svg width="19" height="32" viewBox="0 0 20 36" fill="none" xmlns="http://www.w3.org/2000/svg" className="h-full">
                  <path opacity="0.4" d="M13.2156 9.00221L0 18.6931L0 33.0375C0 35.4922 3.03565 36.7195 4.81522 34.9808L18.371 21.7359C20.543 19.6136 20.543 16.1617 18.371 14.0394L13.2156 9.00221Z" fill="#164A41"/>
                  <path d="M0 2.76626V18.6961L13.2156 9.00524L4.81522 0.797406C3.03565 -0.915755 0 0.311585 0 2.76626Z" fill="#164A41"/>
                </svg>
              </button>
            </div>
         </div>
        <div className="text-center font-poppins headline text-[#164A41] mx-4">
          <div className="inline-block px-[140px]">Payment Methods</div>
            <div className="border-2 border-[#164A41] mt-2 rounded-lg p-4 w-full flex flex-wrap">
              <img src="Paypal.png" alt="" className="mr-6 ml-4" />
              <img src="amex.png" alt="" className="mx-6" />
              <img src="Visa.png" alt="" className="mx-6" />
              <img src="Mastercard.png" alt="" className="ml-6 mr-4" />
          </div>
        </div>
      </div>
      <HoverImages/>
      <div className="w-full border-2 border-solid h-0 border-gray-400 rounded-3xl my-5"></div>
      <div className="text-center">
        <h1 className="text-2xl mb-2 font-poppins text-[#164A41]">Central BioHub GmbH, Neuendorfstrasse 17, 16761 Hennigsdorf, Germany | Call: +49 3302 230 91 66 | Email: info@centralbiohub.com</h1>
        <h1 className="text-2xl mb-2 font-poppins text-[#164A41]">© 2023 www.centralbiohub.de All Rights Reserved - Link to Imprint here</h1>
      </div>
    </div>
  )
}
