import { type NextPage } from "next";
import Head from "next/head";

//import { api } from "~/utils/api";
import Header from "~/components/header";
import Sidebar from "~/components/sidebar";
import Search from "~/components/search";

type test = {
  num: number,
  obj: string | test
}

const Home: NextPage = () => {
  //const samples = api.samples.getAll.useQuery({ pages: 1, lines: 1, search: ""})
  const samples = api.samples.test.useQuery({obj: "juju"})
  console.table(samples.data)

  const t: test = {num: 0, obj: { num: 2, obj: "hi"}}
  console.log(t)

  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-gray-200 min-h-screen overflow-x-hidden">
        <Header/>
        <span className="grid grid-cols-7">
            <Sidebar/>
        </span>
      </main>
    </>
  );
};

export default Home;

/*const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};*/
