import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Header from "~/components/overall/header";
import Sidebar from "~/components/overall/sidebar";
import SimpleSlider from "~/components/home/carousel"
import Testimonials from "~/components/home/testimonials";

type test = {
  num: number,
  obj: string | test
}

const Home: NextPage = () => {
  //const samples = api.samples.getAll.useQuery({ pages: 1, lines: 1, search: ""})
  const samples = api.samples.test.useQuery({obj: "juju"})
  console.table(samples.data)

  const t: test = {num: 0, obj: { num: 2, obj: "hi"}}
  console.log(t)

  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <main className="bg-gray-200 min-h-screen overflow-x-hidden overflow-y-hidden">
        <Header/>
          <span className="grid grid-cols-7">
            <div className="grid col-span-1">
              <Sidebar/>  
            </div>     
            <div className="grid col-span-6 h-[95vh] overflow-y-auto">
              <Content/>
            </div>         
          </span>
      </main>
    </>
  );
};

export default Home;

/*const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};*/

const Content: React.FC = () => {

  return(
    <div>
      <div className="flex flex-row w-full items-center justify-center">
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-2">Welcome to CBH!</h1>
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <img src="/banner.png" alt="Banner" className="m-auto w-full"/>
      <div className="flex flex-row w-full items-center justify-center">
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-1">Biospecimen Categories</h1>
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <div className="mt-5">
        <SimpleSlider/>
      </div>
      <div className="flex flex-row w-full items-center justify-center">
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-2">Our Partners - Your Suppliers</h1>
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <div className="flex flex-row w-full items-center justify-center">
        <a href="https://indorivclinical.com/" className="w-full ml-5 mr-20 sponsor-link">
          <img src="/image_13.png" alt="Indoriv Clinical Logo" className="imgSponsor m-auto"/>
        </a>
        <a href="https://audubonbio.com/" className="w-full ml-5 mr-5 sponsor-link">
          <img src="/image 16.png" alt="Audobon Bioscience Logo" className="imgSponsor m-auto"/>
        </a>
        <a href="https://www.innov-research.com/" className="w-full ml-5 mr-20 sponsor-link">
          <img src="/new.png" alt="Innovate Research Logo" className="imgSponsor m-auto"/>
        </a>
      </div>
      <div className="flex flex-row w-full items-center justify-center">
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
        <h1 className="headline whitespace-nowrap ml-20 mr-20 mb-2">Testimonials</h1>
        <div className="w-full border-2 border-solid h-3 border-gray-400 rounded-3xl m-5"></div>
      </div>
      <div className="mt-5">
        <Testimonials/>
      </div>

    </div>
  )
}
