import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import HeaderNEW from "~/components/overall/header";
import useWindowSize from "~/utils/window";
import Footer from "~/components/overall/footer";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="fixed max-h-full min-h-full min-w-full max-w-full overflow-hidden bg-gray-100">
        <div className="flex flex-col">
          <HeaderNEW />
          <Content />
        </div>
      </div>
    </>
  );
};

export default Home;

const Content: React.FC = () => {
  const windowSize = useWindowSize();

  return (
    <div className="max-h-[calc(100vh-80px)] overflow-x-hidden overflow-y-scroll font-poppins">
      <div className="mt-10 flex w-full flex-row items-center justify-center">
        <div className="m-5  h-3 w-full rounded-3xl border-gray-400"></div>
        <h1 className="headline mb-2 ml-20 mr-20 whitespace-nowrap">
          Tutorial Expert Search
        </h1>
        <div className="m-5  h-3 w-full rounded-3xl border-gray-400"></div>
      </div>
      <div className="flex w-full flex-row items-center justify-center">
        <h1 className="mx-20 mb-2 whitespace-nowrap text-xl">
          The expert search is explained here
        </h1>
      </div>

      <Image
            src="/expertFilter.png"
            alt="expert Search Filter"
            width={1920}
            height={1080}
            className="z-20 cursor-pointer"
      />

      <div className="flex w-[50%] flex-row items-center justify-start mt-8">
            {/* Button to toggle the NOT state */}
            <button
              className={`ml-5 w-[6rem] whitespace-nowrap rounded-l-2xl border-2 border-solid border-[#F1B24A] px-4 py-1 text-center text-lg bg-[#4D774E] text-white`}
            >
              NOT
            </button>
            {/* Button to set the link state to AND */}
            <button
              className={`w-[6rem] whitespace-nowrap border-y-2 border-solid border-[#F1B24A] px-4 py-1 text-center text-lg bg-[#F1B24A] text-white`}
            >
              AND
            </button>
            {/* Button to set the link state to OR */}
            <button
              className={`w-[6rem] whitespace-nowrap rounded-r-2xl border-2 border-solid border-[#F1B24A] px-4 py-1 text-center text-lg bg-[#4D774E] text-white`}
            >
              OR
            </button>                       
      </div>
      <div className="mt-3 ml-6">
        The buttons for AND or OR indicate how the different filters should be connected within the group. <br />
        Underneath you select the column which should be filtered and in which form and then you enter the value.
      </div>

      <div className="flex w-[50%] flex-row items-center justify-start ml-5 mt-14">
            {/* Button to add a new group */}
            <button
              className="w-[10rem] whitespace-nowrap rounded-l-2xl border-2 border-solid border-[#9DC88D] bg-[#9DC88D] px-4 py-1 text-center text-lg text-white"
            >
              New Group
            </button>
            {/* Button to add a new filter rule */}
            <button
              className="w-[10rem] whitespace-nowrap border-2 border-solid border-y-[#9DC88D] bg-[#9DC88D] px-4 py-1 text-center text-lg text-white"
            >
              New Rule
            </button>
            {/* Button to toggle the activated state of the group */}
            <button
              className="w-[10rem] whitespace-nowrap rounded-r-2xl border-2 border-solid border-orange-400 bg-orange-400 px-4 py-1 text-center text-lg text-white"
            >
              deactivate
            </button>
            {/* Button to toggle the optional state of the group */}
            <button
              className="relative w-fit whitespace-nowrap rounded-2xl bg-[#F1B24A] px-3 py-1 text-center text-lg text-white outline-none transition hover:bg-[#e8b25b]"
            >
              ?
            </button>
          </div>
          <div className="mt-2 flex w-full flex-wrap p-4">
            <div className="ml-2">
              <h2><b>New Group Button</b></h2>
              <div>
                - adds a new group to a list of groups <br/>
                - This button, when clicked, appends <br/>
                 a new group object to the list of groups
              </div>
            </div>
            <div className="ml-5">
              <h2><b>New Rule Button</b></h2>
              <div>
                - adds a new filter rule to a list of filters <br/>
                -  Clicking this button appends a new filter<br/>
                 rule to the list of filters
              </div>
            </div>
            <div className="ml-5">
              <h2><b>Deactivate Button</b></h2>
              <div>
                - toggles the activation state of the group <br/>
                - This button switches the &apos;activated&apos; state<br/>
                 of the group between &apos;activate&apos; and &apos;deactivate&apos;
              </div>
            </div>
            <div className="ml-5">
              <h2><b>Optional Button</b></h2>
              <div>
                - Toggles the optional state of the group <br/>
                - Clicking this button toggles the &apos;!&apos; or &apos;?&apos; symbol,<br/>
                 representing the optional state of the group
              </div>
            </div>
          </div>         
      
      <div className="mt-14">
      <Image
              src="/expertSearchRule.png"
              alt="new rule expert search"
              className="mx-4"
              width={1500}
              height={1080}
            />
            <div className="mt-2 flex w-full flex-wrap p-4">
            <div className="ml-2 mt-3">
              <h2><b>Column Selection</b></h2>
              <div>
                - here you select the column to filter <br/>
                - renders a dropdown or input for selecting a column
              </div>
            </div>
            <div className="ml-5 mt-3">
              <h2><b>Type Select</b></h2>
              <div>
                -  renders a dropdown or input for selecting a filter type <br/>
                -  selection how the value should be filtered
              </div>
            </div>
            <div className="ml-5 mt-3">
              <h2><b>Choose values</b></h2>
              <div>
                - Renders a component for choosing filter values <br/>
                - choose the values that should be filtered
              </div>
            </div>
            <div className="ml-5 mt-3">
              <h2><b>Avtivate/Deactivate Filter and Delete Button</b></h2>
              <div>
                - Toggles the activation state of the filter <br/>
                - sets the filter to activate or deactivate <br/>
                - delete Button deletes the Rule
              </div>
            </div>
            <div className="ml-5 mt-3">
              <h2><b>Optional Button</b></h2>
              <div>
                - Toggles the optional state of the group <br/>
                - Clicking this button toggles the &apos;!&apos; or &apos;?&apos; symbol,<br/>
                 representing the optional state of the group
              </div>
            </div>
          </div> 
      <div>

      </div>
      </div>
      

      <div className="m-auto mb-10 mt-5 flex items-center justify-center">
        <div className="headline mx-4 text-center text-[#164A41]">
          <div className="inline-block px-32 ">Follow Our Journey!</div>
          {/*social media icons*/}
          <div className="mt-2 flex w-full flex-wrap rounded-lg border-2 border-[#164A41] p-4">
            <Image
              src="/facebook.png"
              alt=""
              className="mx-4"
              width={32}
              height={60}
            />
            <Image
              src="/twitter.png"
              alt=""
              className="mx-4"
              width={75}
              height={60}
            />
            <Image
              src="/youtube.png"
              alt=""
              className="mx-4"
              width={75}
              height={60}
            />
            <Image
              src="/instagram.png"
              alt=""
              className="mx-4"
              width={60}
              height={60}
            />
            <Image
              src="/linkedin.png"
              alt=""
              className="mx-4"
              width={66}
              height={60}
            />
          </div>
        </div>
        <div className="headline mx-16 text-center text-[#164A41]">
          <div className="inline-block px-[140px] ">Testimonials</div>
          <div className="mt-2 flex w-full justify-end rounded-lg border-2 border-[#164A41]">
            <div className="flex flex-1 flex-col justify-center text-center text-2xl font-semibold">
              Look What People
              <br />
              Say About Us!
            </div>
            <button className="flex h-full rounded-br-lg rounded-tr-lg border-[#F1B24A] bg-[#F1B24A] px-8 py-[32px] text-lg">
              <svg
                width="19"
                height="32"
                viewBox="0 0 20 36"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
                className="h-full"
              >
                <path
                  opacity="0.4"
                  d="M13.2156 9.00221L0 18.6931L0 33.0375C0 35.4922 3.03565 36.7195 4.81522 34.9808L18.371 21.7359C20.543 19.6136 20.543 16.1617 18.371 14.0394L13.2156 9.00221Z"
                  fill="#164A41"
                />
                <path
                  d="M0 2.76626V18.6961L13.2156 9.00524L4.81522 0.797406C3.03565 -0.915755 0 0.311585 0 2.76626Z"
                  fill="#164A41"
                />
              </svg>
            </button>
          </div>
        </div>
        <div className="headline mx-4 text-center text-[#164A41]">
          <div className="inline-block px-[140px]">Payment Methods</div>
          {/*payment icons*/}
          <div className="mt-2 flex w-full flex-wrap rounded-lg border-2 border-[#164A41] p-4">
            <Image
              src="/Paypal.png"
              alt=""
              className="ml-4 mr-6"
              width={55}
              height={60}
            />
            <Image
              src="/amex.png"
              alt=""
              className="mx-6"
              width={67}
              height={60}
            />
            <Image
              src="/Visa.png"
              alt=""
              className="mx-6"
              width={90}
              height={60}
            />
            <Image
              src="/Mastercard.png"
              alt=""
              className="ml-6 mr-4"
              width={91}
              height={60}
            />
          </div>
        </div>
      </div>      
      <Footer />
    </div>
  );
};
