import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import Header from "~/components/header";
import Sidebar from "~/components/sidebar";
import { useEffect, useState } from "react";
import Footer from "~/components/footer";
import Filter from "~/components/filter";
import Group from "~/components/group";

import { BiCartAdd, BiDetail, BiX } from "react-icons/bi"

import OverlayTrigger from 'react-bootstrap/OverlayTrigger';
import Popover from 'react-bootstrap/Popover';
import { Samples } from "@prisma/client";
import { set } from "zod";

type Filter = {
  cbhMasterID: string | undefined,
  cbhDonorID: string | undefined,
  cbhSampleID: string | undefined,
  price: { 
    min: number | undefined, 
    max: number | undefined 
  },
  matrix: string[],
  quantity: {
    min: number | undefined,
    max: number | undefined,
  },
  unit: string[],
  labParameter: string[],
  resultInterpretation: string[],
  //resultNumerical
  resultUnit: string[],
  diagnosis: string[],
  ICDCode: string[]
}

const Expertsearch: NextPage = () => {
  return (
    <>
      <Head>
        <title>Central BioHub</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      
      <div className="bg-gray-200 min-h-screen overflow-y-hidden">
        <Header/>
        <span className="grid grid-cols-7">
            <div className="col-span-1">
              <Sidebar/>
            </div>
            <div className="col-span-6 h-[95vh] overflow-y-auto">
              <Content/>
            </div>
        </span>
      </div>
    </>
  );
};

export default Expertsearch;

const Content: React.FC = () => {
  const defaultFilter: Filter = {
    cbhMasterID: undefined, 
    cbhDonorID: undefined, 
    cbhSampleID: undefined,
    price: {
      min: undefined,
      max: undefined,
    },
    matrix: [],
    quantity: {
      min: undefined,
      max: undefined,
    },
    unit: [],
    labParameter: [],
    resultInterpretation: [],
    resultUnit: [],
    diagnosis: [],
    ICDCode: []
  }
  const defaultShow: boolean[] = []

  const [page, setPage] = useState<number>(1)
  const [pagelength, setPagelength] = useState<number>(50)
  const [search, setSearch] = useState<string | undefined>()
  const [filter, setFilter] = useState<Filter>(defaultFilter)
  const [range, setRange] = useState<number[]>([])

  for(let i = 0; i < pagelength; i++){
    defaultShow.push(false)
  }

  const handlePageLengthChange = (length: number) => {
    setPagelength(length);
  };

  const [show, setShow] = useState<boolean[]>(defaultShow)

  const { data: samples, refetch: refetchSamples } = api.samples.getAll.useQuery(
      { pages: page, lines: pagelength, search: search, filter: filter }
  )

  const { data: count, refetch: refetchCount } = api.samples.count.useQuery()

  useEffect(() => {
    void refetchSamples()
  }, [search, page, pagelength, refetchSamples])

  useEffect(() => {
    const newRange = [];
    if (count !== undefined){
    const num = Math.ceil(count / pagelength);
    for (let i = 1; i <= num; i++) {
        newRange.push(i);
    }
    }
    setRange(newRange);
  }, [count, pagelength])

  type stringFilter = {
    link: string,
    filter: string[],
    groups: stringFilter[]
    }

  type numberFilter = {
    link: string,
    filter: string[],
    groups: numberFilter[]
    }

  const updateState = (index: number) => {
    const newArray = show.map((item, i) => {
      if(index === i){
        return !item
      } else {
        return item
      }
    })
    setShow(newArray)
  }

  return(
      <div className="w-full overflow-x-hidden font-poppins">
        {/*<input type="text" onKeyDown={e => {
          if(e.key === "Enter"){
            setSearch(e.currentTarget.value)
            e.currentTarget.value = ""
          }
        }}/>*/}

        <h1 className="text-5xl mt-5 ml-5 mb-2 text-green-900">Expert Search</h1>

        <Group/>
        <Filter/>

        <div className="mx-4 my-5">
          <table className="w-full text-lg border-separate border-spacing-y-1 max-h-[50vh] overflow-y-auto">
            <thead>
              <tr className="bg-[rgb(131,182,94)] text-gray-100 font-extralight">
                <th className="py-2 font-extralight border-dotted rounded-l-xl border-black border-r-2">Cart</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">CBHDonorID</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">CBHSampleID</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Details</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Matrix</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Quantity</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Unit</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Age</th>
                <th className="py-2 font-extralight border-dotted border-black border-r-2">Gender</th>
                <th className="py-2 font-extralight rounded-r-xl">Price</th>
              </tr>
            </thead>
            <tbody>
              {samples?.map((sample, index) => (
                <>
                  <tr key={index} className="text-center">
                    <td className="items-center text-2xl bg-gray-300 rounded-l-xl"><button><BiCartAdd className="relative top-1"/></button></td>
                    <td className="py-2 px-3 bg-gray-300">{sample.CBH_Donor_ID}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.CBH_Sample_ID}</td>
                    <td className="items-center text-2xl bg-gray-300"><button onClick={() => {updateState(index)}}><BiDetail className="relative top-1"/></button></td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Matrix}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Quantity}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Unit}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Age}</td>
                    <td className="py-2 px-3 bg-gray-300">{sample.Gender}</td>
                    <td className="py-2 px-3 bg-gray-300 rounded-r-xl">{sample.Price} €</td> 
                  </tr>
                  <tr className={`mx-5 ${show[index] ? "" : "hidden"}`}>
                    <td colSpan={2} className="px-5 bg-gray-200">
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">General Data</strong>
                        <span>CBH Master ID:</span> {sample.CBH_Master_ID ?? "NaN"}
                        <span>Storage Temperature:</span> {sample.Storage_Temperature ?? "NaN"}
                        <span>Freeze Thaw Cycles:</span> {sample.Freeze_Thaw_Cycles ?? "NaN"}
                        <span>Infectious Disease Test Result:</span> {(sample.Infectious_Disease_Test_Result !== null && sample.Infectious_Disease_Test_Result !== "") ? sample.Infectious_Disease_Test_Result : "NaN"}
                        <span>Sample Condition:</span> {sample.Sample_Condition ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={2}>
                      <div className="grid grid-cols-2 ">
                        <strong className="col-span-2">Donor</strong>
                        <span>Age:</span> {sample.Age ?? "NaN"}
                        <span>Gender:</span> {sample.Gender ?? "NaN"}
                        <span>Ethnicity:</span> {sample.Ethnicity ?? "NaN"}
                        <strong className="col-span-2 mt-2">Ethics</strong>
                        <span>Procurement Type:</span> {sample.Procurement_Type ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={2}>
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">Laboratory</strong>
                        <span>Lab Parameter</span> {sample.Lab_Parameter ?? "NaN"}
                        <span>Result Raw:</span> {sample.Result_Raw ?? "NaN"}
                        <span>Result Unit:</span> {sample.Result_Unit ?? "NaN"}
                        <span>Interpretation:</span> {sample.Result_Interpretation ?? "NaN"}
                        <span>Cut Off Raw:</span> {sample.Cut_Off_Raw ?? "NaN"}
                        <span>Cut Off Unit:</span> {sample.Result_Unit ?? "NaN"}
                        <span>Test Method:</span> {sample.Test_Method ?? "NaN"}
                        <span>Test System:</span> {sample.Test_System ?? "NaN"}
                        <span>Test System Manuf.:</span> {sample.Test_System_Manufacturer ?? "NaN"}
                      </div>
                    </td>
                    <td className="border-l-2 border-solid border-gray-300 px-2" colSpan={4}>
                      <div className="grid grid-cols-2">
                        <strong className="col-span-2">Clinical Diagnosis</strong>
                        <span>Diagnosis:</span> {(sample.Diagnosis !== null && sample.Diagnosis !== "") ? sample.Diagnosis : "NaN"}
                        <span>Diagnosis Remarks:</span> {(sample.Diagnosis_Remarks !== null && sample.Diagnosis_Remarks !== "") ? sample.Diagnosis_Remarks : "NaN"}
                        <strong className="col-span-2 mt-2">Preanalytics</strong>
                        <span>Collection Country:</span> {sample.Country_of_Collection ?? "NaN"}
                        <span>Collection Date:</span> {sample.Date_of_Collection?.toDateString() ?? "NaN"}
                      </div>
                    </td>
                  </tr>
                </>
              ))}
            </tbody>
          </table>
        </div>
        <div className="flex flex-row w-full items-center justify-center">
        <Footer range={range} page={page} setPage={setPage}/>

        <p>Show rows</p>
        <select name="pagelength" id="pagelength" onChange={e => handlePageLengthChange(parseInt(e.target.value))}>
          <option value={50}>50</option>
          <option value={100}>100</option>
          <option value={150}>150</option>
          <option value={200}>200</option>
          <option value={250}>250</option>
          <option value={500}>500</option>
          <option value={1000}>1000</option>
        </select>
        </div>
        
        
        

      </div>
  )
}